name: twitter_auth
description: A Flutter plugin to sign in with Twitter on Android & iOS.
version: 0.0.4
homepage: https://github.com/StackTiger/flutter_auth/tree/master/packages/twitter_auth

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_auth_core:
    path: packages/flutter_auth_core
  http: ^0.13.4
  meta: ^1.1.8
  oauth1: ^2.0.0
  quiver: ^3.0.1+1
  xml_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
