name: flutter_auth_core
description: A common interface for twitter_auth and github_auth plugins.
version: 0.0.4
homepage: https://github.com/StackTiger/flutter_auth/tree/master/packages/flutter_auth_core

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  http: ^0.13.4
  meta: ^1.7.0
  oauth1: ^2.0.0
  quiver: ^3.0.1+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
